# Generated by Django 5.1.6 on 2025-03-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sume_lccv', '0002_remove_projetos_area_tecnologica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financiadores',
            old_name='financiador',
            new_name='nome',
        ),
    ]
