# Generated by Django 5.1.6 on 2025-03-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sume_lccv', '0003_rename_financiador_financiadores_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areastecnologicas',
            old_name='area_tecnologica',
            new_name='nome',
        ),
    ]
